[package]
name = "labrpc"
version = "0.1.4"
authors = ["Jing Yang <ditsing@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.6"
futures = { version = "0.3.5", features = ["thread-pool"] }
parking_lot = "0.11.0"
rand = "0.7.3"
tokio = { version = "0.2.22", features = ["rt-threaded", "time"] }
