[package]
name = "labrpc"
version = "0.1.0"
authors = ["Jing Yang <ditsing@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.6"
futures = { version = "0.3.5", features =[ "thread-pool" ] }
rand = "0.7.3"
tokio-timer = "0.3.0-alpha.6"
