[package]
name = "labrpc"
version = "0.1.5"
authors = ["Jing Yang <ditsing@gmail.com>"]
description = "A RPC framework for testing"
edition = "2018"
license = "MIT"

[dependencies]
bytes = "0.5.6"
crossbeam-channel = "0.5.0"
futures = { version = "0.3.5", features = ["thread-pool"] }
parking_lot = "0.11.0"
rand = "0.7.3"
tokio = { version = "0.3", features = ["rt-multi-thread", "time", "parking_lot"] }
